#!/usr/bin/env bash
#
# commit-msg hook: strips AI tool attribution lines from commit messages.
# Removes lines matching Co-Authored-By trailers or other markers that
# reference AI assistants (Claude, Cursor, Copilot, ChatGPT, etc.).
#
# Usage: passed the commit message file path as $1 by git/pre-commit.

set -euo pipefail

COMMIT_MSG_FILE="$1"

if [ ! -f "$COMMIT_MSG_FILE" ]; then
    exit 0
fi

AI_TOOLS="[Cc]laude|[Cc]ursor|[Cc]opilot|[Cc]hat[Gg][Pp][Tt]|[Aa]nthropic|[Oo]pen[Aa][Ii]|[Gg]emini|[Dd]eep[Ss]eek|[Ww]indsurf|[Cc]line|[Aa]ider"

# Filter out:
#   - Co-Authored-By trailers referencing AI tools
#   - "Generated by" / "Created with" / etc. attribution lines
grep -viE \
    -e "^co-authored-by:.*($AI_TOOLS)" \
    -e "^\\s*(🤖\\s*)?(generated|created|assisted|powered|made|written)\\s+(by|with|using)\\s+.*($AI_TOOLS)" \
    "$COMMIT_MSG_FILE" > "${COMMIT_MSG_FILE}.tmp" || true

mv "${COMMIT_MSG_FILE}.tmp" "$COMMIT_MSG_FILE"

# Strip trailing blank lines
if [ -s "$COMMIT_MSG_FILE" ]; then
    # Read file, remove trailing newlines, write back
    perl -0777 -pe 's/\n+\z/\n/' "$COMMIT_MSG_FILE" > "${COMMIT_MSG_FILE}.tmp"
    mv "${COMMIT_MSG_FILE}.tmp" "$COMMIT_MSG_FILE"
fi
